// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

// qawf_integral
Rcpp::List qawf_integral(double alpha, double lower, double upper, double abs_tol, double rel_tol, unsigned int size);
RcppExport SEXP fracdet_qawf_integral(SEXP alphaSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP abs_tolSEXP, SEXP rel_tolSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< double >::type abs_tol(abs_tolSEXP);
    Rcpp::traits::input_parameter< double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type size(sizeSEXP);
    __result = Rcpp::wrap(qawf_integral(alpha, lower, upper, abs_tol, rel_tol, size));
    return __result;
END_RCPP
}
// theoreticalVpr
NumericVector theoreticalVpr(NumericVector& gr, NumericVector& hr, double H, double sigma2, int nlevels);
RcppExport SEXP fracdet_theoreticalVpr(SEXP grSEXP, SEXP hrSEXP, SEXP HSEXP, SEXP sigma2SEXP, SEXP nlevelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector& >::type gr(grSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type hr(hrSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< int >::type nlevels(nlevelsSEXP);
    __result = Rcpp::wrap(theoreticalVpr(gr, hr, H, sigma2, nlevels));
    return __result;
END_RCPP
}
