# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qawf_integral <- function(alpha, lower, upper, abs_tol = 0.0, rel_tol = 1e-7, size = 1e5L) {
    .Call('fracdet_qawf_integral', PACKAGE = 'fracdet', alpha, lower, upper, abs_tol, rel_tol, size)
}

simulateFbmCpp <- function(n, H) {
    .Call('fracdet_simulateFbmCpp', PACKAGE = 'fracdet', n, H)
}

theoreticalWaveletVarCpp <- function(gr, hr, H, sigma2, nlevels) {
    .Call('fracdet_theoreticalWaveletVarCpp', PACKAGE = 'fracdet', gr, hr, H, sigma2, nlevels)
}

